name: rotana

on:
  schedule:
    - cron: '0 */21 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script
        run: |
          python_output=$(python ressources/kuw/rotlbc.py)
          echo "$python_output" > ressources/kuw/rotlbc.m3u8

      - name: Create Directories via FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: .
          remoteDir: /mdtvr.42web.io/htdocs/ressources/kuw
          transfers: |
            mkdir ressources
            mkdir ressources/kuw

      - name: Upload file via FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ressources/kuw
          remoteDir: /mdtvr.42web.io/htdocs/ressources/kuw

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
        run: |
          git config --local user.email "no@no.no"
          git config --local user.name "no"
          git add ressources/kuw/rotlbc.m3u8
          git commit -m "rotana updates"
          git push origin master
