name: rotana

on:
  schedule:
    - cron: '0 */21 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4     

      - name: Run Script
        run: |
         python_output=$(python ressources/kuw/rotlbc.py)
         echo "$python_output" >> ressources/kuw/rotlbc.m3u8        

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Commit and Push Changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
        run: |
          git config --local user.email "no@no.no"
          git config --local user.name "no"
          git add ressources/kuw/rotlbc.m3u8
          git commit -m "rotana updates"
          git push origin main

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
        run: |
          # Guardar el archivo en un directorio temporal para conservarlo al cambiar de rama
          cp ressources/kuw/rotlbc.m3u8 /tmp/rotlbc.m3u8
          
          # Verificar si la rama gh-pages existe; si no, crearla
          if git ls-remote --exit-code origin gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
          else
            echo "gh-pages branch not found, creating it..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "<html><body><h1>GitHub Pages initialized</h1></body></html>" > index.html
            git add index.html
            git commit -m "Initialize gh-pages branch"
          fi
          
          # Crear la carpeta para GitHub Pages y copiar el archivo desde el directorio temporal
          mkdir -p stream
          cp /tmp/rotlbc.m3u8 stream/rotlbc.m3u8
          git add stream/rotlbc.m3u8
          git commit -m "Update rotlbc.m3u8"
          git push origin gh-pages
