name: Actualizar Lista M3U

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Esto es para ejecutar a las 2 AM todos los días

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MDTV2/requirements.txt  # Si tienes un archivo requirements.txt

      - name: Run script to update list
        run: python MDTV2/script.py
