name: Actualizar lista M3U

on:
  push:
    paths:
      - "MDTV2/peliculas.txt"
  workflow_dispatch:

jobs:
  actualizar_lista:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r MDTV2/requirements.txt || true  # Si no tienes este archivo, lo omitirá

      - name: Ejecutar script
        run: python MDTV2/script.py

      - name: Subir lista M3U generada
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add MDTV2/lista.m3u
          git commit -m "Actualizar lista M3U automáticamente"
          git push
